language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

install:
  - mvn clean compile -DskipTests
  - mvn test
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn --quiet install -DskipTests -Pdefault,docker

after_success:
  - mvn deploy -DskipTests -Pdocker

before_deploy:
  - docker tag -f marketreaction/analyse:$TRAVIS_BUILD_NUMBER marketreaction/analyse:latest

deploy:
  - docker push marketreaction/analyse:latest